export const USER_MAP = {
    "65a546ae4a8f64e8f88fb89e": {
        UserName: "fridaklo",
        Role: "Retail Banking Customer",
        Section: "retail",
        Employer: "Deloitte Mexico",
        EmploymentType: "FullTime",
        JobTitle: "Accountant",
        IncomeAmount: 5500,
        Currency: "USD",
        IncomeFrequency: "Monthly",
    },
    "66fe219d625d93a100528224": {
        UserName: "hellyrig",
        Role: "Retail Banking Customer",
        Section: "retail",
        Employer: null,
        EmploymentType: "Freelance",
        JobTitle: "Freelance Designer",
        IncomeAmount: null,
        Currency: "USD",
        IncomeFrequency: "Irregular",
    },
    "67a1000000000000000000001": {
        UserName: "marcowenz",
        Role: "Bank Operations Admin",
        Section: "backoffice",
        Employer: "Leafy Bank",
        EmploymentType: "FullTime",
        JobTitle: "Bank Operations Admin",
        IncomeAmount: null,
        Currency: "USD",
        IncomeFrequency: null,
    },
    "67a1000000000000000000002": {
        UserName: "anaruiz",
        Role: "Risk Analyst",
        Section: "backoffice",
        Employer: "Leafy Bank",
        EmploymentType: "FullTime",
        JobTitle: "Risk Analyst",
        IncomeAmount: null,
        Currency: "USD",
        IncomeFrequency: null,
        Url: "https://fsi-fraud-detection.industrysolutions.prod.corp.mongodb.com/?userEmail=ainhoa.mugica%40mongodb.com&sessionGoal=Development+%2F+Test",
    },
    "67a1000000000000000000003": {
        UserName: "davidpark",
        Role: "Risk Manager",
        Section: "backoffice",
        Employer: "Leafy Bank",
        EmploymentType: "FullTime",
        JobTitle: "Risk Manager",
        IncomeAmount: null,
        Currency: "USD",
        IncomeFrequency: null,
        Url: "https://fsi-fraud-detection.industrysolutions.prod.corp.mongodb.com/",
    },
    "67a1000000000000000000004": {
        UserName: "sophiachen",
        Role: "Relationship Manager",
        Section: "backoffice",
        Employer: "Leafy Bank",
        EmploymentType: "FullTime",
        JobTitle: "Relationship Manager",
        IncomeAmount: null,
        Currency: "USD",
        IncomeFrequency: null,
        Url:"https://leafy-bank-ui.industrysolutions.prod.corp.mongodb.com/asset-portfolio",
    },
    "67a1000000000000000000005": {
        UserName: "lucastorres",
        Role: "Payments Operations",
        Section: "backoffice",
        Employer: "Leafy Bank",
        EmploymentType: "FullTime",
        JobTitle: "Payments Operations",
        IncomeAmount: null,
        Currency: "USD",
        IncomeFrequency: null,
        Url: "https://fsi-payments-processing.industrysolutions.prod.corp.mongodb.com/",
    },
};

export const USER_LIST = Object.entries(USER_MAP).map(([id, details]) => ({
    id,
    name: details.UserName,
    role: details.Role,
    section: details.Section,
    employer: details.Employer,
    employmentType: details.EmploymentType,
    jobTitle: details.JobTitle,
    incomeAmount: details.IncomeAmount,
    currency: details.Currency,
    incomeFrequency: details.IncomeFrequency,
    url: details.Url ?? null,

}));